# dataset: Yelp
# inter_feat_path: "dataset/Amazon/Book_overMovie_5core.inter"
show_progress: False
topk: [5, 10, 20, 50]
metrics: ["Hit", "NDCG", "MRR", "Precision"]

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: business_id
RATING_FIELD: stars
TIME_FIELD: date
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
  inter: [user_id, business_id, stars, date, session_id, tm_wday, tm_hour]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
val_interval:
  stars: "(0,inf)"
  date: "[1546272000,1577721600]"

# training and evaluation
epochs: 500
train_batch_size: 2048
eval_batch_size: 2048
valid_metric: NDCG@10
eval_args:
  split: { "LS": "valid_and_test" }
  order: TO
neg_sampling: ~
