# Base
train_batch_size: 1024
neg_sampling: ~

# SASRec
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: "CE"

# Dataset
SESSION_ID_FIELD: session_id
WDAY_FIELD: tm_wday
HOUR_FIELD: tm_hour

# Ours
learning_rate: 0.005

train_stage: "pretrain" # pretrain
pretrain_epochs: 50
pre_model_path: ""

emb_CL: "in"
tau: 0.05
weight: 0.0001
weight_item_CL_global: 0.0001
weight_item_CL_local: 0.0001
weight_subseq_CL_global: 0.0001
weight_subseq_CL_local: 0.0001
